[[mgr.prepend_keymap]]
on = "<C-p>"
run = 'shell -- qlmanage -p "$@"'

[[mgr.prepend_keymap]]
on  = "<C-n>"
run = 'shell -- open "$PWD"'
desc = "Open current directory in Finder"

# --- Override default create behavior ---

# Disable default "a" (create file OR dir depending on trailing slash)
[[mgr.prepend_keymap]]
on  = "a"
run = "noop"

# Lowercase a → create file only
[[mgr.prepend_keymap]]
on   = "a"
run  = "create --force"
desc = "Create file"


# Uppercase A → create directory only
[[mgr.prepend_keymap]]
on   = "A"
run  = "create --dir --force"
desc = "Create directory"
