
[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

select = [
  "ALL" 
]
ignore = [
    "D103",
    "C901",
    "ANN003",
    "W291",
    "T201", 
    "COM812",
    "ERA001",  # Use of `except:` detected
    "ANN001",
    "ANN002",
    "D105",
    "ANN205",
    "ANN202",
    "ANN201",
    "D415",
    "D400",
    "W293",
    "ANN204",
    "D107",
    "D101",
    "FBT002",
    "N803",
    "N806",
    "EM101",
    "TRY003",
    "D102",
    "ANN101",
    "D203",    # One blank line before class docstring
    "D212",    # Multi-line summary first line
    "PLR0913", # Too many arguments
    "Q000",    # Single quotes found but double quotes preferred
    "D205",    # 1 blank line required between summary line and description
    "D213",    # Multi-line docstring summary should start at the second line
  "D214",    # Section is missing a section title
  "D215",    # Section underline is over-indented
  "D210",      # No whitespaces allowed surrounding docstring text
  "D404",      # First word of the docstring should not be This
  "D401",      # First line should be in imperative mood
  "D202",
  "D410",
  "D411",
  "D413",
  "D200",
  "SIM108",


    
]
ignore-init-module-imports = true
line-length = 120
# preview = true
show-fixes = true
target-version = "py38"


[tool.ruff.flake8-quotes]
docstring-quotes = "double"
multiline-quotes = "double"


[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10


[tool.ruff.per-file-ignores]
# https://beta.ruff.rs/docs/rules/
"__init__.py" = ["F401","F403","F405",]
"tests/*" = ["ANN", "ARG", "INP001", "S101",]


[tool.ruff.pylint]
max-args = 15
max-branches = 20
max-returns = 10
max-statements = 80


[tool.ruff.flake8-tidy-imports]
ban-relative-imports = "all"

