[general]
import = [
    "~/.config/alacritty/themes/themes/pastel_dark.toml"
]

[colors.cursor]
cursor = "#00c2ff"

[font]
size = 9.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"


[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

# [debug]
# log_level = "Debug"


[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"

# Disable Alacritty's default Ctrl zoom bindings.
[[keyboard.bindings]]
key = "="
mods = "Control"
action = "None"

[[keyboard.bindings]]
key = "+"
mods = "Control"
action = "None"

[[keyboard.bindings]]
key = "-"
mods = "Control"
action = "None"

# Remap zoom to Ctrl+Shift plus/minus.
[[keyboard.bindings]]
key = "="
mods = "Control|Shift"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "+"
mods = "Control|Shift"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "-"
mods = "Control|Shift"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "_"
mods = "Control|Shift"
action = "DecreaseFontSize"
