[general]
import = [
    "~/.config/alacritty/themes/themes/pastel_dark.toml"
]

[window]
padding = {x=3, y=2}
option_as_alt = "Both"

[terminal]
osc52 = "CopyPaste"

[colors.cursor]
cursor = "#00c2ff"

[font]
size = 12.0


[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"


[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[debug]
log_level = "Debug"

